name: Feature Request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: Is your feature request related to a problem? Please describe it.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like.
      placeholder: I would like to see...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternatives you've considered.
      placeholder: Another approach would be...
    validations:
      required: false
