#!/usr/bin/env bash
# =============================================================================
# scripts/setup-secrets.sh — Generate .env with random secrets from .env.example
# =============================================================================
# Usage:
#   bash scripts/setup-secrets.sh         # generate .env (error if exists)
#   bash scripts/setup-secrets.sh --force # overwrite existing .env
# =============================================================================
set -euo pipefail

ENV_FILE=".env"
EXAMPLE_FILE=".env.example"
FORCE="${1:-}"

# -- Guard: refuse to overwrite unless --force is passed ----------------------
if [ -f "$ENV_FILE" ] && [ "$FORCE" != "--force" ]; then
    echo "Error: $ENV_FILE already exists. Use --force to overwrite." >&2
    exit 1
fi

# -- Guard: .env.example must exist -------------------------------------------
if [ ! -f "$EXAMPLE_FILE" ]; then
    echo "Error: $EXAMPLE_FILE not found. Are you in the project root?" >&2
    exit 1
fi

# -- Generate secrets (quietly — no stdout echo) ------------------------------
SERVER_MASTER_SECRET="$(openssl rand -base64 32 | tr -d '\n')"
SESSION_SECRET="$(openssl rand -hex 32 | tr -d '\n')"
POSTGRES_PASSWORD="$(openssl rand -base64 24 | tr -d '\n')"

# -- Write .env ---------------------------------------------------------------
cat > "$ENV_FILE" << EOENV
# =============================================================================
# Virtual PO Box — Environment Configuration (auto-generated)
# =============================================================================
# Generated by scripts/setup-secrets.sh
# =============================================================================

# -- General ------------------------------------------------------------------
NODE_ENV=development
APP_MODE=development

# -- Database (PostgreSQL) ----------------------------------------------------
DATABASE_URL="postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432/wahabox?schema=public"

# -- Redis (rate limiting) ----------------------------------------------------
REDIS_URL="redis://localhost:6379"

# -- Secrets ------------------------------------------------------------------
SERVER_MASTER_SECRET="${SERVER_MASTER_SECRET}"
SESSION_SECRET="${SESSION_SECRET}"

# -- Cloudflare Turnstile -----------------------------------------------------
NEXT_PUBLIC_TURNSTILE_SITE_KEY=""
TURNSTILE_SECRET_KEY=""

# -- Deployment ---------------------------------------------------------------
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
HOST_PORT=3000

# -- Amazon SES (email) -------------------------------------------------------
SES_FROM_ADDRESS="noreply@wahabox.example.com"
AWS_REGION=us-east-1
# AWS_ACCESS_KEY_ID=CHANGE_ME
# AWS_SECRET_ACCESS_KEY=CHANGE_ME

# Application URL (used in email links)
APP_URL="https://wahabox.localhost/"
EOENV

echo "✅ .env generated successfully." >&2
