import { execSync } from 'node:child_process'
import { writeFileSync, existsSync } from 'node:fs'

const versionPath = new URL('../version.json', import.meta.url)

let sha
try {
  sha = execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim()
} catch {
  // If version.json already exists (pre-generated by deploy.sh on host),
  // keep the existing file instead of overwriting with "unknown"
  if (existsSync(versionPath)) {
    process.exit(0)
  }
  sha = process.env.GIT_SHA || 'unknown'
}
const date = new Date().toISOString()

writeFileSync(
  new URL('../version.json', import.meta.url),
  JSON.stringify({ sha, date }, null, 2) + '\n',
)
